apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webserver
  labels:
    app: webserver-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver-worker
  template:
    metadata:
      labels:
        app: webserver-worker
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-webserver-svc
  labels:
    app: webserver-worker
spec:
  ports:
  - port: 80
    name: httpbiasa
  selector:
    app: webserver-worker
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-webserver-ingress
  labels:
    app: webserver-worker
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/default-backend: "my-webserver-svc"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: coba.its.ac.id
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: my-webserver-svc
          servicePort: 80
  tls:
  - hosts:
    - coba.its.ac.id
    secretName: app-tls

