apiVersion: v1
kind: Pod
metadata:
  name: alpine-demo
  labels:
    app: coba-alpine
spec:
  containers:
  - name: coba-alpine-container
    image: alpine
    resources:
      requests:
        cpu: "0.1"
        memory: "64Mi"
      limits:
        cpu: "0.5"
        memory: "64Mi"
    command:
    - sh
    - -c
    - |
      while true;
      do
        sleep 2000;
      done

